/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thecodinginterface.interfaces;

import org.junit.Test;
import static org.junit.Assert.*;

public class InterfacesAppTest {

}
