/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thecodinginterface.utils;

import org.junit.Test;
import static org.junit.Assert.*;

public class TciUtilsTest {
    @Test public void testSomeLibraryMethod() {

    }
}
