/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thecodinginterface.references;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReferencesAppTest {
    @Test public void testAppHasAGreeting() {
    }
}
